### ISSUE TITLE
Wrong order in loader-settings.ts

### ISSUE THREAD

**Issue by gergogy** [fictionco/fiction#185] opened 2020-04-03 05:16 UTC
**Reason for this issue**
I tried to rename the `/blog` route in my project, but not worked. I followed the [docs](https://factor.dev/docs/basic-example). I think the problem is the order of importing `factor-settings.js`  in `loader-settings.ts`.
It should be the last one to everything can be overridable.
![image](https://user-images.githubusercontent.com/21192274/78325834-1ca09500-7579-11ea-86d2-fbebfeae1061.png)

**Steps to Reproduce**
Follow the steps in [Basic Example](https://factor.dev/docs/basic-example), then run `npx factor dev` in CLI.

**UPDATE**
`loader-styles.less` has same issue.
![image](https://user-images.githubusercontent.com/21192274/78328052-7d7e9c00-757e-11ea-97cc-75649c234a60.png)

**Comment by arpowers** [comment] 2020-04-03 07:42
Ya that's a strange output actually, it shouldn't be including `node_modules` in there and referencing the package directly. How do you have your project setup?

**Comment by arpowers** [comment] 2020-04-03 07:43
typical output: 

<img width="1023" alt="Screen Shot 2020-04-03 at 1 43 24 AM" src="https://user-images.githubusercontent.com/308134/78336411-88203d80-754c-11ea-8b71-ed126421c0af.png">

**Comment by gergogy** [comment] 2020-04-03 08:44
I followed the guide. https://factor.dev/docs/basic-example
But currently I can't share anything else, because my macbook just died...

**Comment by arpowers** [comment] 2020-04-03 20:38
can you give me a link to your code or a pic of your file structure? Something is up with the node_modules folder.

**Comment by gergogy** [comment] 2020-04-03 21:11
Sorry, but I can't. I just ended up with playing around with the code and sent these comments, then  it's suddenly shutted down and doesn't turn back on. So it was only on local, nothing pushed, even git was not inited.

I remember that, I imported bulma, aws-sdk, ldapjs and made 1 or 2 components and views, nothing special.

**Comment by gergogy** [comment] 2020-04-04 18:01
So, my computer suddenly working again... so I made a screenshot of folder structure. Maybe the package.json in the playground mess with the app, I'm not 100% sure because these are separated folders and projects...
I usually work on gitlab, but I pushed this to GitHub too, and I invited you to collaborate, so you are able to clone...
![image](https://user-images.githubusercontent.com/21192274/78457804-2fb48180-76ad-11ea-94a6-834acf79f1e2.png)

**Comment by arpowers** [comment] 2020-04-04 18:34
Ah, i think i see. Do you have nested apps? Which is your working directory? (Where you run commands)

I may be able to fix this, or accomdate if there is a use case

**Comment by gergogy** [comment] 2020-04-04 18:39
`app` folder is the working directory, playground is just for trying out things like ldap. If you can fix this, please feel free to push, I invited you to collaborate.

**Comment by arpowers** [comment] 2020-04-06 17:14
@gergogy found the issue here, globbing problem. Should be fixed after i push a patch today.

**Comment by gergogy** [comment] 2020-04-06 17:36
@arpowers thanks!
![](https://media.giphy.com/media/IdD98kNkrI8EVFGocX/giphy.gif)

**Closed as completed** 2020-04-06 17:47 UTC

**Comment by gergogy** [comment] 2020-04-06 17:54
@arpowers Maybe you can use this as a ref for a more efficient solution:
https://github.com/prettier/prettier/issues/1358

**Comment by arpowers** [comment] 2020-04-06 18:10
Saw that, wasn't working. The issue is that `node_modules` is in the path, but shouldn't be in the path after a certain point.

**Comment by arpowers** [comment] 2020-04-06 18:11
Ultimately the current solution is fine, probably costs like 100ms on build.
